# docker-compose.yml
version: "3"
services:
  backend:
    restart: on-failure
    build: ./backend
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ddo_ecommerce_backend
      DB_PASSWORD: 1234
      DB_DATABASE: ddo_ecommerce
      DB_DIALECT: postgres
      APP_PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/
      - /app/node_modules
      - ./static:/app/static
      - logs:/app/logs

  postgres:
    image: postgres:11
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: ddo_ecommerce_backend
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ddo_ecommerce

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: kayhan@disqet.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "5050:80"

  web:
    restart: always
    build: ./nginx
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./static:/static

volumes:
  logs: